<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Verifyuser extends Model
{
    //
    protected $guarded=[];

    public function user(){
        return $this->belongsTo('App\User','user_id');
    }
    public function getRouteKeyName()
    {
        return 'token'; // TODO: Change the autogenerated stub
    }
}
